swagger: "2.0"
info:
  version: 1.0.0
  title: examdatabase
  description: My cool app
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /admin/auth:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Returns all examples
  /admin/addAdmin:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              role:
                type: string
      responses:
        200:
          description: Returns all examples
  /admin/getPassword:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        200:
          description: Returns all examples
  /admin/addExaminer:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              user:
                type: object

      responses:
        200:
          description: Returns all examples
  /admin/deleteExaminer:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              id:
                type: string
      responses:
        200:
          description: Returns all examples
  /admin/getMetaData:
    get:
      tags:
        - Examples
      responses:
        200:
          description: Returns all examples
  /admin/getAdmins:
    get:
      tags:
        - Examples
      responses:
        200:
          description: Returns all examples
  /admin/updateAdmin:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              role:
                type: string
      responses:
        200:
          description: Returns all examples
  /admin/updateExaminer:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              user:
                type: object

      responses:
        200:
          description: Returns all examples
  /admin/verifyToken:
    post:
      tags:
        - Examples
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              token:
                type: string

      responses:
        200:
          description: Returns all examples
  /admin/addMultipleUsers:
    post:
      tags:
        - User
      summary: Get user data
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              users:
                type: array
                items:
                  type: object
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/addUniversity:
    post:
      tags:
        - User
      summary: Get user data
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              university:
                type: array
                items:
                  type: object
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/updateUniversity:
    post:
      tags:
        - User
      summary: Get user data
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              university:
                type: array
                items:
                  type: object
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/getUniversities:
    get:
      tags:
        - User
      summary: Get user data
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/getAllExaminers:
    get:
      tags:
        - User
      summary: Get user data

      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/assign:
    post:
      tags:
        - User
      summary: Get user data
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              e_id:
                type: string
              formDetails:
                type: object
              travelDetails:
                type: object
              payDetails:
                type: object
              createdAt:
                type: string
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/assignments:
    get:
      tags:
        - User
      summary: Get user data
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/deleteAssignment:
    post:
      tags:
        - User
      summary: Get user data
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              id:
                type: string
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /admin/updateAssignment:
    post:
      tags:
        - User
      summary: Get user data
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              e_id:
                type: string
              formDetails:
                type: object
              travelDetails:
                type: object
              payDetails:
                type: object
              createdAt:
                type: string
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
